PMM-5980 Add suspend pxc
percona-platform/dbaas-controller pull request #102
Opened 2020-12-04 20:07 UTC by askomorokhov

https://jira.percona.com/browse/PMM-5980

https://github.com/percona-platform/dbaas-api/pull/70

2020-12-09 21:30 UTC, askomorokhov commented on tests/xtradbcluster/xtra_db_cluster_test.go
> +					CpuM:        200,
Decreased values to have the ability to test it on eks single node.

2020-12-11 13:11 UTC, BupycHuk requested changes

2020-12-11 14:09 UTC, askomorokhov commented on service/cluster/xtra_db_cluster.go
> +		if req.Params.Pxc.ComputeResources.CpuM > 0 || req.Params.Pxc.ComputeResources.MemoryBytes > 0 {
Reused `computeResources` func

2020-12-11 14:44 UTC, BupycHuk approved these changes

2020-12-11 14:51 UTC, percona-csalguero approved these changes

2020-12-16 14:10 UTC, BupycHuk approved these changes

2020-12-16 14:11 UTC, merged