PMM-7090 Return disk size value.
percona-platform/dbaas-controller pull request #105
Opened 2020-12-09 09:05 UTC by BupycHuk

2020-12-09 14:22 UTC, askomorokhov requested changes

2020-12-09 14:22 UTC, askomorokhov commented on tests/init.go
> +	pmmServerAddressF := flag.String("pmm.server-address", "pmm-server:443", "PMM Server Address [PMM_SERVER_ADDRESS].") // FIXME: fix this once we start using CI.
Let's make it empty by default. And set only for specific for. monitoring tests.

2020-12-10 11:12 UTC, askomorokhov approved these changes

2020-12-10 11:47 UTC, percona-csalguero approved these changes

2020-12-11 14:49 UTC, merged