PMM-6805 Exclude test package from check
percona-platform/dbaas-controller pull request #78
Opened 2020-10-30 14:04 UTC by percona-csalguero

In go 1.15, AST analyzer in go-consistent reports that the test package is not being used in the main dbass module. It is true but it is a testing package so we can exclude it from checks.

2020-10-30 16:42 UTC, AlekSi requested changes
Please add another line that actually checks tests module

2020-10-30 16:43 UTC, AlekSi commented
@BupycHuk That might be an argument to extract API tests into own repo

2020-11-02 18:53 UTC, BupycHuk approved these changes

2020-11-03 08:23 UTC, AlekSi approved these changes
LGTM, but there is a merge conflict now

2020-11-03 12:47 UTC, merged